-- QRスタンプラリー用データベース定義（Supabase）
-- 何度実行しても同じ状態になるように書いています。既存のデータは削除しません。
-- 旧版から更新するときは、景品発送先（氏名・住所など）を survey_responses から
-- prize_shipping に自動で移し替えます（移し替えを確認できない場合は、何も変更せずに中止します）。
-- SupabaseのSQL Editorに全体を貼り付けて Run してください。
begin;

-- ============================================================
-- 1. 基本テーブル
-- ============================================================
create table if not exists public.scan_events (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  stamp_code text not null check (stamp_code in ('river','bridge','fish','island','water','goal')),
  scanned_at timestamptz not null default now(),
  user_agent text
);

create table if not exists public.stamp_claims (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  stamp_code text not null check (stamp_code in ('river','bridge','fish','island','water','goal')),
  sequence integer not null check (sequence between 1 and 6),
  first_scanned_at timestamptz not null default now(),
  unique (participant_id, stamp_code),
  unique (participant_id, sequence)
);

-- アンケートの回答。氏名・住所などの個人情報は、別テーブル prize_shipping に分けて保存する。
create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  submitted_at timestamptz not null default now(),
  satisfaction integer check (satisfaction between 1 and 5),
  memorable_spot text,
  comment text,
  prize_requested boolean not null default false,
  workshop_participation text,
  unique (participant_id)
);

-- 旧版の列名 completion_participant_id を participant_id にそろえる
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'survey_responses' and column_name = 'completion_participant_id'
  ) then
    alter table public.survey_responses rename column completion_participant_id to participant_id;
  end if;
end $$;

alter table public.survey_responses alter column prize_requested set default false;

-- 初回取得（true）と再スキャン（false）を区別する
alter table public.scan_events add column if not exists is_first_claim boolean;

-- 列追加前の行は、参加者×スタンプごとの最初の読み取りを初回取得とみなして埋める
update public.scan_events e
set is_first_claim = (e.id = f.first_id)
from (
  select participant_id, stamp_code, min(id) as first_id
  from public.scan_events
  group by participant_id, stamp_code
) f
where e.is_first_claim is null
  and e.participant_id = f.participant_id
  and e.stamp_code = f.stamp_code;

create index if not exists scan_events_scanned_at_idx on public.scan_events (scanned_at desc, id desc);
create index if not exists scan_events_participant_idx on public.scan_events (participant_id);

-- アンケート：暗渠ワークショップ（ちよだ家プロジェクト）への参加有無
alter table public.survey_responses add column if not exists workshop_participation text;
alter table public.survey_responses drop constraint if exists survey_workshop_participation_check;
alter table public.survey_responses add constraint survey_workshop_participation_check check (
  workshop_participation is null
  or workshop_participation in ('attended', 'not_attended', 'unsure')
);

-- ============================================================
-- 2. 景品発送先（個人情報）：アンケート回答とは別のテーブルに保存する
-- ============================================================
create table if not exists public.prize_shipping (
  participant_id text primary key references public.survey_responses (participant_id) on delete cascade,
  created_at timestamptz not null default now(),
  recipient_name text not null,
  postal_code text not null,
  address text not null,
  phone text not null,
  consent boolean not null default false,
  privacy_version text
);

-- 旧版（survey_responses に発送先の列があった版）からの移し替え。
-- 全件の移し替えを確認できたときだけ、旧い列を削除する。確認できなければ全体を中止する。
do $$
declare
  v_unmigrated integer;
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'survey_responses' and column_name = 'recipient_name'
  ) then
    alter table public.survey_responses drop constraint if exists survey_prize_fields_check;
    alter table public.survey_responses add column if not exists privacy_version text;

    insert into public.prize_shipping
      (participant_id, created_at, recipient_name, postal_code, address, phone, consent, privacy_version)
    select r.participant_id, r.submitted_at, r.recipient_name, r.postal_code, r.address, r.phone,
           coalesce(r.consent, false), r.privacy_version
    from public.survey_responses r
    where r.recipient_name is not null and r.postal_code is not null
      and r.address is not null and r.phone is not null
    on conflict (participant_id) do nothing;

    select count(*) into v_unmigrated
    from public.survey_responses r
    where (r.recipient_name is not null or r.postal_code is not null
           or r.address is not null or r.phone is not null)
      and not exists (select 1 from public.prize_shipping s where s.participant_id = r.participant_id);

    if v_unmigrated > 0 then
      raise exception '発送先の移し替えを確認できない行が % 件あります。何も変更せずに中止します。', v_unmigrated;
    end if;

    alter table public.survey_responses
      drop column recipient_name, drop column postal_code, drop column address,
      drop column phone, drop column consent, drop column privacy_version;
  end if;
end $$;

-- 入力値の範囲（旧版で保存済みの行は検査せず、新しく保存・更新する行だけを検査する）
alter table public.prize_shipping drop constraint if exists prize_shipping_values_check;
alter table public.prize_shipping add constraint prize_shipping_values_check check (
  length(recipient_name) between 1 and 100
  and length(postal_code) between 3 and 20
  and length(address) between 1 and 300
  and length(phone) between 5 and 30
  and consent
) not valid;

-- ============================================================
-- 3. 管理者・テスト参加者の除外
-- ============================================================
-- 管理画面を閲覧できるユーザー（Supabase Authのユーザーを登録する）
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- 集計・CSV・スプレッドシートから外す参加者（動作確認のデータなど）。データ自体は削除しない。
create table if not exists public.excluded_participants (
  participant_id text primary key,
  reason text,
  created_at timestamptz not null default now()
);

alter table public.scan_events enable row level security;
alter table public.stamp_claims enable row level security;
alter table public.survey_responses enable row level security;
alter table public.prize_shipping enable row level security;
alter table public.excluded_participants enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_users where user_id = auth.uid());
$$;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

-- 旧ポリシー（匿名の直接INSERT、ログイン済み全員のSELECT）を削除
drop policy if exists "scan_events_anon_insert" on public.scan_events;
drop policy if exists "stamp_claims_anon_insert" on public.stamp_claims;
drop policy if exists "survey_anon_insert" on public.survey_responses;
drop policy if exists "scan_events_authenticated_select" on public.scan_events;
drop policy if exists "stamp_claims_authenticated_select" on public.stamp_claims;
drop policy if exists "survey_authenticated_select" on public.survey_responses;
drop policy if exists "scan_events_admin_select" on public.scan_events;
drop policy if exists "stamp_claims_admin_select" on public.stamp_claims;
drop policy if exists "survey_admin_select" on public.survey_responses;
drop policy if exists "prize_shipping_admin_select" on public.prize_shipping;
drop policy if exists "excluded_participants_admin_select" on public.excluded_participants;

-- 閲覧は admin_users に登録された管理者だけ。
-- 書き込みは record_scan / submit_survey / admin_* 関数経由だけ（テーブルへの直接書き込みは不可）。
create policy "scan_events_admin_select" on public.scan_events
for select to authenticated using ((select public.is_admin()));

create policy "stamp_claims_admin_select" on public.stamp_claims
for select to authenticated using ((select public.is_admin()));

create policy "survey_admin_select" on public.survey_responses
for select to authenticated using ((select public.is_admin()));

create policy "prize_shipping_admin_select" on public.prize_shipping
for select to authenticated using ((select public.is_admin()));

create policy "excluded_participants_admin_select" on public.excluded_participants
for select to authenticated using ((select public.is_admin()));

revoke all on public.scan_events, public.stamp_claims, public.survey_responses, public.admin_users,
  public.prize_shipping, public.excluded_participants from public, anon, authenticated;
grant select on public.scan_events, public.stamp_claims, public.survey_responses,
  public.prize_shipping, public.excluded_participants to authenticated;

-- ============================================================
-- 4. 表示用の補助関数
-- ============================================================
create or replace function public.stamp_name(p_code text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case p_code
    when 'river' then '川の入口'
    when 'bridge' then '橋'
    when 'fish' then '魚'
    when 'island' then '島'
    when 'water' then '水辺'
    when 'goal' then 'ゴール'
  end;
$$;

create or replace function public.workshop_label(p_code text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case p_code
    when 'attended' then '参加した'
    when 'not_attended' then '参加していない'
    when 'unsure' then 'わからない／覚えていない'
  end;
$$;

-- ブラウザ情報（user agent）から端末の種類を判定する。iPhoneのUAには "Mac OS X" も含まれるため、iPhoneを先に判定する。
create or replace function public.device_type(p_user_agent text)
returns text
language sql
stable
set search_path = ''
as $$
  select case
    when p_user_agent is null or btrim(p_user_agent) = '' then '不明'
    when p_user_agent ilike '%ipad%' then 'iPad'
    when p_user_agent ilike '%iphone%' or p_user_agent ilike '%ipod%' then 'iPhone'
    when p_user_agent ilike '%android%' and p_user_agent ilike '%mobile%' then 'Android'
    when p_user_agent ilike '%android%' then 'Androidタブレット'
    when p_user_agent ilike '%windows%' then 'Windows PC'
    when p_user_agent ilike '%macintosh%' then 'Mac'
    when p_user_agent ilike '%cros%' then 'Chromebook'
    when p_user_agent ilike '%linux%' then 'Linux PC'
    else 'その他'
  end;
$$;

-- ============================================================
-- 5. 管理画面用のビュー（security_invoker：閲覧者本人の権限で動くので、上のRLS＝管理者のみが効く）
-- ============================================================
-- 読み取り履歴（1回の読み取り＝1行）
create or replace view public.v_admin_scans with (security_invoker = true) as
select e.id,
       e.scanned_at,
       e.participant_id,
       e.stamp_code,
       public.stamp_name(e.stamp_code) as stamp_name,
       e.is_first_claim,
       case when e.is_first_claim then '初回取得' when e.is_first_claim is false then '再スキャン' end as scan_type,
       public.device_type(e.user_agent) as device,
       coalesce(e.user_agent like '% [resend]', false) as is_resend,
       e.user_agent,
       exists (select 1 from public.excluded_participants x where x.participant_id = e.participant_id) as is_excluded
from public.scan_events e;

-- 参加者ごとの状況（1人＝1行）
create or replace view public.v_admin_participants with (security_invoker = true) as
with ev as (
  select participant_id,
         count(*) as total_scans,
         count(*) filter (where is_first_claim is false) as rescans,
         min(scanned_at) as first_scan_at,
         max(scanned_at) as last_scan_at,
         (array_agg(user_agent order by scanned_at, id))[1] as first_user_agent
  from public.scan_events
  group by participant_id
), cl as (
  select participant_id,
         count(*) as stamps,
         max(first_scanned_at) as last_claim_at,
         max(first_scanned_at) filter (where stamp_code = 'river') as river_at,
         max(first_scanned_at) filter (where stamp_code = 'bridge') as bridge_at,
         max(first_scanned_at) filter (where stamp_code = 'fish') as fish_at,
         max(first_scanned_at) filter (where stamp_code = 'island') as island_at,
         max(first_scanned_at) filter (where stamp_code = 'water') as water_at,
         max(first_scanned_at) filter (where stamp_code = 'goal') as goal_at,
         string_agg(public.stamp_name(stamp_code), ' → ' order by sequence) as route,
         jsonb_agg(jsonb_build_object('stamp_code', stamp_code, 'sequence', sequence, 'at', first_scanned_at)
                   order by sequence) as claims
  from public.stamp_claims
  group by participant_id
)
select ev.participant_id,
       coalesce(cl.stamps, 0)::integer as stamps,
       coalesce(cl.stamps, 0) = 6 as completed,
       case when cl.stamps = 6 then cl.last_claim_at end as completed_at,
       cl.river_at, cl.bridge_at, cl.fish_at, cl.island_at, cl.water_at, cl.goal_at,
       cl.route,
       cl.claims,
       ev.first_scan_at,
       ev.last_scan_at,
       ev.total_scans,
       ev.rescans,
       public.device_type(ev.first_user_agent) as device,
       exists (select 1 from public.survey_responses r where r.participant_id = ev.participant_id) as survey_submitted,
       (select r.workshop_participation from public.survey_responses r where r.participant_id = ev.participant_id) as workshop_participation,
       exists (select 1 from public.excluded_participants x where x.participant_id = ev.participant_id) as is_excluded
from ev
left join cl using (participant_id);

-- 旧版の管理画面が使っているビュー。除外した参加者を含めないように更新する。
create or replace view public.v_dashboard_summary with (security_invoker = true) as
select
  (select count(*) from public.v_admin_participants where not is_excluded) as participants,
  (select count(*) from public.v_admin_participants where not is_excluded and completed) as completers,
  (select count(*) from public.v_admin_scans where not is_excluded) as total_scans;

create or replace view public.v_spot_stats with (security_invoker = true) as
select stamp_code, count(*) as total_scans,
       count(distinct participant_id) as unique_participants
from public.v_admin_scans
where not is_excluded
group by stamp_code order by stamp_code;

create or replace view public.v_participant_routes with (security_invoker = true) as
select c.participant_id, c.stamp_code, c.sequence, c.first_scanned_at,
       exists (select 1 from public.excluded_participants x where x.participant_id = c.participant_id) as is_excluded
from public.stamp_claims c
order by c.participant_id, c.sequence;

alter view public.v_admin_scans set (security_invoker = true);
alter view public.v_admin_participants set (security_invoker = true);
alter view public.v_dashboard_summary set (security_invoker = true);
alter view public.v_spot_stats set (security_invoker = true);
alter view public.v_participant_routes set (security_invoker = true);

-- ============================================================
-- 6. スタンプの記録・アンケート送信（参加者の端末から呼ばれる関数）
-- ============================================================
create or replace function public.is_completed(p_participant_id text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select count(distinct stamp_code) = 6
  from public.stamp_claims
  where participant_id = p_participant_id;
$$;

revoke all on function public.is_completed(text) from public;
grant execute on function public.is_completed(text) to anon, authenticated;

create or replace function public.record_scan(
  p_participant_id text,
  p_stamp_code text,
  p_user_agent text default null
)
returns table (claimed boolean, claim_sequence integer, completed boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_claim integer;
begin
  if length(p_participant_id) not between 4 and 64
     or p_stamp_code not in ('river','bridge','fish','island','water','goal') then
    raise exception 'invalid scan';
  end if;

  perform pg_advisory_xact_lock(hashtext(p_participant_id));

  -- 初回取得なら stamp_claims に順番付きで保存（2回目以降は何もしない）
  -- 取得済みかを先に確認する。6個そろった後の再スキャンで順番が7になり、
  -- CHECK制約（1〜6）に違反して読み取り自体が保存されなくなるのを防ぐため。
  if not exists (
    select 1 from public.stamp_claims
    where participant_id = p_participant_id and stamp_code = p_stamp_code
  ) then
    insert into public.stamp_claims (participant_id, stamp_code, sequence)
    select p_participant_id, p_stamp_code, count(*)::integer + 1
    from public.stamp_claims
    where participant_id = p_participant_id
    on conflict (participant_id, stamp_code) do nothing
    returning sequence into inserted_claim;
  end if;

  -- 読み取りは初回・再スキャンにかかわらず毎回保存
  insert into public.scan_events (participant_id, stamp_code, user_agent, is_first_claim)
  values (p_participant_id, p_stamp_code, left(p_user_agent, 1000), inserted_claim is not null);

  return query
  select inserted_claim is not null,
         coalesce(inserted_claim, (
           select sc.sequence from public.stamp_claims sc
           where sc.participant_id = p_participant_id
             and sc.stamp_code = p_stamp_code
         )),
         (select count(distinct sc.stamp_code) = 6
          from public.stamp_claims sc
          where sc.participant_id = p_participant_id);
end;
$$;

revoke all on function public.record_scan(text, text, text) from public;
grant execute on function public.record_scan(text, text, text) to anon, authenticated;

-- アンケート送信。6スポット制覇をサーバー側で確認してから保存する。
-- 回答は survey_responses に、景品を希望した場合の発送先は prize_shipping に、同じ処理の中で保存する。
-- 戻り値: 'ok' / 'already_submitted' / 'not_completed' / 'invalid_...'
-- （引数を追加した新版は、旧版の呼び出し方もそのまま受け付ける。初期版の10引数の関数が残っていると、
--   呼び出しが曖昧になり、削除した列も参照してしまうので、先に削除する）
drop function if exists public.submit_survey(text, integer, text, text, boolean, text, text, text, text, boolean);

create or replace function public.submit_survey(
  p_participant_id text,
  p_satisfaction integer,
  p_memorable_spot text default null,
  p_comment text default null,
  p_prize_requested boolean default false,
  p_recipient_name text default null,
  p_postal_code text default null,
  p_address text default null,
  p_phone text default null,
  p_consent boolean default false,
  p_workshop_participation text default null,
  p_privacy_version text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_participant text := btrim(coalesce(p_participant_id, ''));
  v_spot text := nullif(btrim(coalesce(p_memorable_spot, '')), '');
  v_comment text := nullif(btrim(coalesce(p_comment, '')), '');
  v_prize boolean := coalesce(p_prize_requested, false);
  v_name text := nullif(btrim(coalesce(p_recipient_name, '')), '');
  v_postal text := nullif(btrim(coalesce(p_postal_code, '')), '');
  v_address text := nullif(btrim(coalesce(p_address, '')), '');
  v_phone text := nullif(btrim(coalesce(p_phone, '')), '');
  v_workshop text := nullif(btrim(coalesce(p_workshop_participation, '')), '');
  v_privacy_version text := left(nullif(btrim(coalesce(p_privacy_version, '')), ''), 40);
begin
  if length(v_participant) not between 4 and 64 then
    return 'invalid_participant';
  end if;
  if not public.is_completed(v_participant) then
    return 'not_completed';
  end if;
  if p_satisfaction is null or p_satisfaction not between 1 and 5 then
    return 'invalid_satisfaction';
  end if;
  if v_spot is not null and v_spot not in ('river','bridge','fish','island','water','goal') then
    return 'invalid_spot';
  end if;
  if length(v_comment) > 2000 then
    return 'invalid_comment';
  end if;
  if v_workshop is not null and v_workshop not in ('attended', 'not_attended', 'unsure') then
    return 'invalid_workshop';
  end if;

  if v_prize then
    if v_name is null or length(v_name) > 100 then return 'invalid_name'; end if;
    if v_postal is null or v_postal !~ '^[0-9]{3}-?[0-9]{4}$' then return 'invalid_postal'; end if;
    if v_address is null or length(v_address) > 300 then return 'invalid_address'; end if;
    if v_phone is null or v_phone !~ '^[0-9]{10,11}$' then return 'invalid_phone'; end if;
    if not coalesce(p_consent, false) then return 'invalid_consent'; end if;
  end if;

  insert into public.survey_responses (
    participant_id, satisfaction, memorable_spot, comment, prize_requested, workshop_participation
  ) values (
    v_participant, p_satisfaction, v_spot, v_comment, v_prize, v_workshop
  )
  on conflict (participant_id) do nothing;

  if not found then
    return 'already_submitted';
  end if;

  -- 景品を希望しない回答では、個人情報を一切保存しない
  if v_prize then
    insert into public.prize_shipping (
      participant_id, recipient_name, postal_code, address, phone, consent, privacy_version
    ) values (
      v_participant, v_name, v_postal, v_address, v_phone, true, v_privacy_version
    );
  end if;

  return 'ok';
end;
$$;

revoke all on function public.submit_survey(text, integer, text, text, boolean, text, text, text, text, boolean, text, text) from public;
grant execute on function public.submit_survey(text, integer, text, text, boolean, text, text, text, text, boolean, text, text) to anon, authenticated;

-- ============================================================
-- 7. 集計・Googleスプレッドシート同期用の関数
--    Supabaseが正本。スプレッドシートは閲覧・集計用の同期先で、ここから書き戻すことはない。
-- ============================================================
-- API（PostgREST）に公開されないスキーマ。同期トークンのハッシュだけを保存する。
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.sheets_sync_tokens (
  token_hash text primary key,
  created_at timestamptz not null default now()
);
revoke all on private.sheets_sync_tokens from public, anon, authenticated;

-- 同期トークンを発行する（SQL Editorから実行。表示は1回だけで、以前のトークンは無効になる）
--   select private.issue_sheets_token();
create or replace function private.issue_sheets_token()
returns text
language plpgsql
security definer
set search_path = private, public
as $$
declare
  v_token text := replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');
begin
  delete from private.sheets_sync_tokens where true;
  insert into private.sheets_sync_tokens (token_hash)
  values (encode(sha256(convert_to(v_token, 'UTF8')), 'hex'));
  return v_token;
end;
$$;
revoke all on function private.issue_sheets_token() from public, anon, authenticated;

create or replace function private.assert_sheets_token(p_token text)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
begin
  if p_token is null or not exists (
    select 1 from private.sheets_sync_tokens
    where token_hash = encode(sha256(convert_to(p_token, 'UTF8')), 'hex')
  ) then
    raise exception 'invalid sync token' using errcode = '42501';
  end if;
end;
$$;
revoke all on function private.assert_sheets_token(text) from public, anon, authenticated;

-- データが変わったかを調べるための「指紋」。対象のテーブルの全行から計算するので、
-- 追加・変更・削除のどれでも値が変わる（行の数だけでなく、中身が書き換わった場合も検出する）。
-- 先頭の 'export-v2' は、出力の形式を変えたときに値を変えて、全体を書き直させるための印。
create or replace function private.sheets_fingerprint()
returns text
language sql
stable
set search_path = public, private
as $$
  select md5(concat_ws('|', 'export-v2',
    (select count(*) || ':' || coalesce(sum(hashtextextended(t::text, 0)), 0) from public.scan_events t),
    (select count(*) || ':' || coalesce(sum(hashtextextended(t::text, 0)), 0) from public.stamp_claims t),
    (select count(*) || ':' || coalesce(sum(hashtextextended(t::text, 0)), 0) from public.survey_responses t),
    (select count(*) || ':' || coalesce(sum(hashtextextended(t::text, 0)), 0) from public.prize_shipping t),
    (select count(*) || ':' || coalesce(sum(hashtextextended(t::text, 0)), 0) from public.excluded_participants t)
  ));
$$;
revoke all on function private.sheets_fingerprint() from public, anon, authenticated;

-- 管理画面とスプレッドシートの「概要」に共通する集計。除外した参加者は含めない。
create or replace function private.stats_json()
returns jsonb
language sql
stable
set search_path = public, private
as $$
  with pa as (select * from public.v_admin_participants),
  p as (select * from pa where not is_excluded),
  sc as (select * from public.v_admin_scans where not is_excluded),
  cl as (
    select c.* from public.stamp_claims c
    where not exists (select 1 from public.excluded_participants x where x.participant_id = c.participant_id)
  ),
  sv as (
    select r.* from public.survey_responses r
    where not exists (select 1 from public.excluded_participants x where x.participant_id = r.participant_id)
  )
  select jsonb_build_object(
    'summary', jsonb_build_object(
      'participants', (select count(*) from p),
      'completers', (select count(*) from p where completed),
      'total_scans', (select count(*) from sc),
      'rescans', (select count(*) from sc where is_first_claim is false),
      'surveys', (select count(*) from sv),
      'prize_requests', (select count(*) from sv where prize_requested),
      'avg_satisfaction', (select round(avg(satisfaction)::numeric, 2) from sv),
      'excluded_participants', (select count(*) from pa where is_excluded)
    ),
    -- 獲得数別の人数（どこで離脱しているか）
    'funnel', (
      select jsonb_agg(jsonb_build_object(
        'stamps', k,
        'exact', (select count(*) from p where p.stamps = k),
        'at_least', (select count(*) from p where p.stamps >= k),
        'ratio', case when (select count(*) from p) > 0
                      then round((select count(*) from p where p.stamps >= k)::numeric / (select count(*) from p), 4) end
      ) order by k)
      from generate_series(1, 6) k
    ),
    -- 日別（日本時間の日付ごと。新しい順）
    'daily', coalesce((
      select jsonb_agg(jsonb_build_object(
        'date', to_char(d, 'YYYY/MM/DD'),
        'new_participants', (select count(*) from p where (p.first_scan_at at time zone 'Asia/Tokyo')::date = d),
        'scans', (select count(*) from sc where (sc.scanned_at at time zone 'Asia/Tokyo')::date = d),
        'completers', (select count(*) from p where p.completed_at is not null
                         and (p.completed_at at time zone 'Asia/Tokyo')::date = d),
        'surveys', (select count(*) from sv where (sv.submitted_at at time zone 'Asia/Tokyo')::date = d)
      ) order by d desc)
      from (
        select (first_scan_at at time zone 'Asia/Tokyo')::date as d from p
        union select (scanned_at at time zone 'Asia/Tokyo')::date from sc
        union select (submitted_at at time zone 'Asia/Tokyo')::date from sv
      ) days
    ), '[]'::jsonb),
    -- ワークショップ参加有無別
    'workshop', (
      select jsonb_agg(jsonb_build_object(
        'label', g.label,
        'responses', (select count(*) from sv where sv.workshop_participation is not distinct from g.code),
        'avg_satisfaction', (select round(avg(sv.satisfaction)::numeric, 2) from sv
                             where sv.workshop_participation is not distinct from g.code),
        'prize_requests', (select count(*) from sv
                           where sv.workshop_participation is not distinct from g.code and sv.prize_requested)
      ) order by g.ord)
      from (values ('attended'::text, '参加した', 1), ('not_attended', '参加していない', 2),
                   ('unsure', 'わからない／覚えていない', 3), (null, '未回答（旧回答など）', 4)) as g(code, label, ord)
    ),
    -- 満足度の分布
    'satisfaction', (
      select jsonb_agg(jsonb_build_object('score', s, 'count', (select count(*) from sv where sv.satisfaction = s))
                       order by s desc)
      from generate_series(1, 5) s
    ),
    -- スポット別
    'spots', (
      select jsonb_agg(jsonb_build_object(
        'stamp_code', g.code,
        'stamp_name', g.name,
        'total_scans', (select count(*) from sc where sc.stamp_code = g.code),
        'unique_participants', (select count(distinct sc.participant_id) from sc where sc.stamp_code = g.code),
        'rescans', (select count(*) from sc where sc.stamp_code = g.code and sc.is_first_claim is false),
        'claimed_participants', (select count(*) from cl where cl.stamp_code = g.code),
        'acquisition_rate', case when (select count(*) from p) > 0
                                 then round((select count(*) from cl where cl.stamp_code = g.code)::numeric
                                            / (select count(*) from p), 4) end
      ) order by g.ord)
      from (values ('river', '川の入口', 1), ('bridge', '橋', 2), ('fish', '魚', 3),
                   ('island', '島', 4), ('water', '水辺', 5), ('goal', 'ゴール', 6)) as g(code, name, ord)
    )
  );
$$;
revoke all on function private.stats_json() from public, anon, authenticated;

-- 変更の有無を調べるだけの軽い問い合わせ（Apps Scriptが5分ごとに呼ぶ）。正しいトークンがないと何も返さない。
create or replace function public.sheets_version(p_token text)
returns text
language plpgsql
security definer
set search_path = public, private
as $$
begin
  perform private.assert_sheets_token(p_token);
  return private.sheets_fingerprint();
end;
$$;
revoke all on function public.sheets_version(text) from public, anon, authenticated;
grant execute on function public.sheets_version(text) to anon;

-- 同期用データを1回のJSONで返す。正しい同期トークンがないと何も返さない。
-- p_include_shipping = true のときだけ、景品発送情報（個人情報）を含める。
-- 除外した参加者のデータは含めない。表示用の文言（初回取得／再スキャンなど）まで整えて返す。
create or replace function public.sheets_export(p_token text, p_include_shipping boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
begin
  perform private.assert_sheets_token(p_token);

  return (
    private.stats_json() || jsonb_build_object(
      'version', private.sheets_fingerprint(),
      'generated_at', now(),
      'scans', coalesce((
        select jsonb_agg(jsonb_build_object(
          'scanned_at', s.scanned_at,
          'participant_id', s.participant_id,
          'stamp_name', s.stamp_name,
          'scan_type', s.scan_type,
          'device', s.device,
          'resend', case when s.is_resend then '再送' end
        ) order by s.scanned_at desc, s.id desc)
        from public.v_admin_scans s
        where not s.is_excluded
      ), '[]'::jsonb),
      'participants', coalesce((
        select jsonb_agg(jsonb_build_object(
          'participant_id', p.participant_id,
          'status', case when p.completed then 'コンプリート' else '途中' end,
          'stamps', p.stamps,
          'river_at', p.river_at,
          'bridge_at', p.bridge_at,
          'fish_at', p.fish_at,
          'island_at', p.island_at,
          'water_at', p.water_at,
          'goal_at', p.goal_at,
          'completed_at', p.completed_at,
          'route', p.route,
          'first_scan_at', p.first_scan_at,
          'last_scan_at', p.last_scan_at,
          'total_scans', p.total_scans,
          'rescans', p.rescans,
          'device', p.device,
          'survey', case when p.survey_submitted then '回答済み' end,
          'workshop', public.workshop_label(p.workshop_participation)
        ) order by p.last_scan_at desc, p.participant_id)
        from public.v_admin_participants p
        where not p.is_excluded
      ), '[]'::jsonb),
      'surveys', coalesce((
        select jsonb_agg(jsonb_build_object(
          'submitted_at', r.submitted_at,
          'participant_id', r.participant_id,
          'satisfaction', r.satisfaction,
          'memorable_spot', public.stamp_name(r.memorable_spot),
          'comment', r.comment,
          'workshop', public.workshop_label(r.workshop_participation),
          'prize', case when r.prize_requested then '希望' else '希望しない' end
        ) order by r.submitted_at desc, r.id desc)
        from public.survey_responses r
        where not exists (select 1 from public.excluded_participants x where x.participant_id = r.participant_id)
      ), '[]'::jsonb),
      'shipping', case when p_include_shipping then coalesce((
        select jsonb_agg(jsonb_build_object(
          'submitted_at', s.created_at,
          'participant_id', s.participant_id,
          'recipient_name', s.recipient_name,
          'postal_code', s.postal_code,
          'address', s.address,
          'phone', s.phone,
          'privacy_version', s.privacy_version
        ) order by s.created_at desc, s.participant_id)
        from public.prize_shipping s
        where not exists (select 1 from public.excluded_participants x where x.participant_id = s.participant_id)
      ), '[]'::jsonb) end
    )
  );
end;
$$;

revoke all on function public.sheets_export(text, boolean) from public, anon, authenticated;
grant execute on function public.sheets_export(text, boolean) to anon;

-- ============================================================
-- 8. 管理画面から呼ぶ関数（管理者以外は実行できない）
-- ============================================================
create or replace function public.admin_stats()
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if not public.is_admin() then
    raise exception 'admin only' using errcode = '42501';
  end if;
  return private.stats_json();
end;
$$;

-- 参加者を集計から除外する／除外を解除する。戻り値は、実際に変更があったか。
create or replace function public.admin_set_excluded(
  p_participant_id text,
  p_excluded boolean,
  p_reason text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id text := btrim(coalesce(p_participant_id, ''));
begin
  if not public.is_admin() then
    raise exception 'admin only' using errcode = '42501';
  end if;
  if length(v_id) not between 4 and 64 then
    raise exception 'invalid participant id';
  end if;

  if coalesce(p_excluded, false) then
    insert into public.excluded_participants (participant_id, reason)
    values (v_id, left(nullif(btrim(coalesce(p_reason, '')), ''), 200))
    on conflict (participant_id) do nothing;
  else
    delete from public.excluded_participants where participant_id = v_id;
  end if;
  return found;
end;
$$;

-- 指定した日時より前に最初の読み取りがあった参加者を、まとめて除外する（本番開始前の動作確認データ用）。
-- 戻り値は、新しく除外した人数。
create or replace function public.admin_exclude_before(
  p_before timestamptz,
  p_reason text default 'テスト（本番開始前）'
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if not public.is_admin() then
    raise exception 'admin only' using errcode = '42501';
  end if;
  if p_before is null then
    raise exception 'p_before is required';
  end if;

  with added as (
    insert into public.excluded_participants (participant_id, reason)
    select participant_id, left(nullif(btrim(coalesce(p_reason, '')), ''), 200)
    from public.scan_events
    group by participant_id
    having min(scanned_at) < p_before
    on conflict (participant_id) do nothing
    returning 1
  )
  select count(*) into v_count from added;
  return v_count;
end;
$$;

-- 除外をすべて解除する。戻り値は、解除した人数。
create or replace function public.admin_clear_excluded()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if not public.is_admin() then
    raise exception 'admin only' using errcode = '42501';
  end if;
  with removed as (
    delete from public.excluded_participants where true returning 1
  )
  select count(*) into v_count from removed;
  return v_count;
end;
$$;

revoke all on function public.admin_stats() from public, anon;
revoke all on function public.admin_set_excluded(text, boolean, text) from public, anon;
revoke all on function public.admin_exclude_before(timestamptz, text) from public, anon;
revoke all on function public.admin_clear_excluded() from public, anon;
grant execute on function public.admin_stats() to authenticated;
grant execute on function public.admin_set_excluded(text, boolean, text) to authenticated;
grant execute on function public.admin_exclude_before(timestamptz, text) to authenticated;
grant execute on function public.admin_clear_excluded() to authenticated;

-- ============================================================
-- 9. Supabaseのダッシュボード（Table Editor）で読みやすくするための日本語ビュー
--    ダッシュボード専用です。ブラウザ（API）からは読めないようにしています。
-- ============================================================
create or replace view public.ja_scan_log with (security_invoker = true) as
select (scanned_at at time zone 'Asia/Tokyo') as "読み取り日時（日本時間）",
       participant_id as "参加者ID",
       stamp_name as "スポット",
       scan_type as "種別",
       device as "端末",
       case when is_resend then '再送' end as "通信失敗後の再送",
       case when is_excluded then '除外' end as "テスト除外",
       user_agent as "ブラウザ情報（元の文字列）"
from public.v_admin_scans
order by scanned_at desc, id desc;

create or replace view public.ja_participants with (security_invoker = true) as
select participant_id as "参加者ID",
       case when completed then 'コンプリート' else '途中' end as "状態",
       stamps as "獲得数",
       (river_at at time zone 'Asia/Tokyo') as "川の入口",
       (bridge_at at time zone 'Asia/Tokyo') as "橋",
       (fish_at at time zone 'Asia/Tokyo') as "魚",
       (island_at at time zone 'Asia/Tokyo') as "島",
       (water_at at time zone 'Asia/Tokyo') as "水辺",
       (goal_at at time zone 'Asia/Tokyo') as "ゴール",
       (completed_at at time zone 'Asia/Tokyo') as "コンプリート日時",
       route as "取得順",
       (first_scan_at at time zone 'Asia/Tokyo') as "最初の読み取り",
       (last_scan_at at time zone 'Asia/Tokyo') as "最後の読み取り",
       total_scans as "読み取り回数",
       rescans as "再スキャン回数",
       device as "端末",
       case when survey_submitted then '回答済み' end as "アンケート",
       public.workshop_label(workshop_participation) as "ワークショップ",
       case when is_excluded then '除外' end as "テスト除外"
from public.v_admin_participants
order by last_scan_at desc, participant_id;

create or replace view public.ja_surveys with (security_invoker = true) as
select (r.submitted_at at time zone 'Asia/Tokyo') as "回答日時（日本時間）",
       r.participant_id as "参加者ID",
       r.satisfaction as "満足度",
       public.stamp_name(r.memorable_spot) as "印象に残った場所",
       r.comment as "コメント",
       public.workshop_label(r.workshop_participation) as "ワークショップ参加",
       case when r.prize_requested then '希望' else '希望しない' end as "景品",
       case when exists (select 1 from public.excluded_participants x where x.participant_id = r.participant_id)
            then '除外' end as "テスト除外"
from public.survey_responses r
order by r.submitted_at desc, r.id desc;

-- 個人情報を含みます。ダッシュボードの管理者以外には見せないでください。
create or replace view public.ja_shipping with (security_invoker = true) as
select (s.created_at at time zone 'Asia/Tokyo') as "回答日時（日本時間）",
       s.participant_id as "参加者ID",
       s.recipient_name as "氏名",
       s.postal_code as "郵便番号",
       s.address as "住所",
       s.phone as "電話番号",
       s.privacy_version as "同意した規約の版",
       case when exists (select 1 from public.excluded_participants x where x.participant_id = s.participant_id)
            then '除外' end as "テスト除外"
from public.prize_shipping s
order by s.created_at desc, s.participant_id;

alter view public.ja_scan_log set (security_invoker = true);
alter view public.ja_participants set (security_invoker = true);
alter view public.ja_surveys set (security_invoker = true);
alter view public.ja_shipping set (security_invoker = true);

-- ============================================================
-- 10. ビューの権限・テーブルの説明
-- ============================================================
revoke all on public.v_dashboard_summary, public.v_spot_stats, public.v_participant_routes,
  public.v_admin_scans, public.v_admin_participants,
  public.ja_scan_log, public.ja_participants, public.ja_surveys, public.ja_shipping
  from public, anon, authenticated;
grant select on public.v_dashboard_summary, public.v_spot_stats, public.v_participant_routes,
  public.v_admin_scans, public.v_admin_participants to authenticated;

comment on table public.scan_events is 'QRコードの全読み取り履歴（取得済みスタンプの再スキャンも含む）';
comment on column public.scan_events.is_first_claim is '初回取得ならtrue、再スキャンならfalse';
comment on column public.scan_events.user_agent is 'ブラウザ情報。通信失敗後の再送は末尾に [resend] が付く';
comment on table public.stamp_claims is '参加者ごとの初回スタンプ取得（取得順 sequence と初回取得時刻）';
comment on table public.survey_responses is 'アンケートの回答（個人情報は含まない）。発送先は prize_shipping';
comment on column public.survey_responses.participant_id is '参加者ID（stamp_claims・scan_events と同じ）';
comment on column public.survey_responses.memorable_spot is '印象に残ったスポット（river / bridge / fish / island / water / goal）';
comment on column public.survey_responses.workshop_participation is 'ワークショップ参加有無（attended=参加した / not_attended=参加していない / unsure=わからない・覚えていない）';
comment on table public.prize_shipping is '景品の発送先（個人情報）。景品を希望した人だけ。管理者以外は読み取れない';
comment on table public.excluded_participants is '集計・CSV・スプレッドシートから外す参加者（テストなど）。データは削除しない';
comment on table public.admin_users is '管理画面を使えるユーザー（Supabase Authのユーザー）';
comment on view public.ja_scan_log is '【ダッシュボード用】読み取り履歴（日本語・日本時間）';
comment on view public.ja_participants is '【ダッシュボード用】参加者ごとの状況（日本語・日本時間）';
comment on view public.ja_surveys is '【ダッシュボード用】アンケート回答（個人情報なし）';
comment on view public.ja_shipping is '【ダッシュボード用】景品発送先（個人情報あり）';

commit;

notify pgrst, 'reload schema';

-- ▼ 管理者の登録（Authentication > Users でユーザーを作成した後、メールアドレスを変えて実行）
-- insert into public.admin_users (user_id)
-- select id from auth.users where email = 'admin@example.com'
-- on conflict do nothing;

-- ▼ Googleスプレッドシート同期用トークンの発行（表示された値をApps Scriptに設定）
-- select private.issue_sheets_token();
