-- QRスタンプラリー拡張版
-- 何度実行しても同じ状態になるように書いています（既存データは削除しません）。
begin;

create table if not exists public.scan_events (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  stamp_code text not null check (stamp_code in ('river','bridge','fish','island','water','goal')),
  scanned_at timestamptz not null default now(),
  user_agent text
);

create table if not exists public.stamp_claims (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  stamp_code text not null check (stamp_code in ('river','bridge','fish','island','water','goal')),
  sequence integer not null check (sequence between 1 and 6),
  first_scanned_at timestamptz not null default now(),
  unique (participant_id, stamp_code),
  unique (participant_id, sequence)
);

create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  completion_participant_id text not null,
  submitted_at timestamptz not null default now(),
  satisfaction integer check (satisfaction between 1 and 5),
  memorable_spot text,
  comment text,
  prize_requested boolean not null default true,
  recipient_name text,
  postal_code text,
  address text,
  phone text,
  consent boolean not null default false,
  unique (completion_participant_id)
);

-- 景品を希望した回答だけ、発送情報と同意を必須にする（既存行は検査しない）
alter table public.survey_responses drop constraint if exists survey_prize_fields_check;
alter table public.survey_responses add constraint survey_prize_fields_check check (
  not prize_requested
  or (recipient_name is not null and postal_code is not null
      and address is not null and phone is not null and consent)
) not valid;

-- 管理画面を閲覧できるユーザー（Supabase Authのユーザーを登録する）
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.scan_events enable row level security;
alter table public.stamp_claims enable row level security;
alter table public.survey_responses enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_users where user_id = auth.uid());
$$;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

-- 旧ポリシー（匿名の直接INSERT、ログイン済み全員のSELECT）を削除
drop policy if exists "scan_events_anon_insert" on public.scan_events;
drop policy if exists "stamp_claims_anon_insert" on public.stamp_claims;
drop policy if exists "survey_anon_insert" on public.survey_responses;
drop policy if exists "scan_events_authenticated_select" on public.scan_events;
drop policy if exists "stamp_claims_authenticated_select" on public.stamp_claims;
drop policy if exists "survey_authenticated_select" on public.survey_responses;
drop policy if exists "scan_events_admin_select" on public.scan_events;
drop policy if exists "stamp_claims_admin_select" on public.stamp_claims;
drop policy if exists "survey_admin_select" on public.survey_responses;

-- 閲覧は admin_users に登録された管理者だけ。
-- 書き込みは record_scan / submit_survey 関数経由だけ（テーブルへの直接書き込みは不可）。
create policy "scan_events_admin_select" on public.scan_events
for select to authenticated using ((select public.is_admin()));

create policy "stamp_claims_admin_select" on public.stamp_claims
for select to authenticated using ((select public.is_admin()));

create policy "survey_admin_select" on public.survey_responses
for select to authenticated using ((select public.is_admin()));

revoke all on public.scan_events, public.stamp_claims, public.survey_responses, public.admin_users
  from public, anon, authenticated;
grant select on public.scan_events, public.stamp_claims, public.survey_responses to authenticated;

-- security_invoker: 閲覧者本人の権限で実行し、上のRLS（管理者のみ）を適用する
create or replace view public.v_dashboard_summary with (security_invoker = true) as
select
  (select count(distinct participant_id) from public.scan_events) as participants,
  (select count(*) from (
    select participant_id from public.stamp_claims
    group by participant_id
    having count(distinct stamp_code) = 6
  ) x) as completers,
  (select count(*) from public.scan_events) as total_scans;

create or replace view public.v_spot_stats with (security_invoker = true) as
select stamp_code, count(*) as total_scans,
       count(distinct participant_id) as unique_participants
from public.scan_events group by stamp_code order by stamp_code;

create or replace view public.v_participant_routes with (security_invoker = true) as
select participant_id, stamp_code, sequence, first_scanned_at
from public.stamp_claims order by participant_id, sequence;

alter view public.v_dashboard_summary set (security_invoker = true);
alter view public.v_spot_stats set (security_invoker = true);
alter view public.v_participant_routes set (security_invoker = true);

revoke all on public.v_dashboard_summary, public.v_spot_stats, public.v_participant_routes
  from public, anon, authenticated;
grant select on public.v_dashboard_summary to authenticated;
grant select on public.v_spot_stats to authenticated;
grant select on public.v_participant_routes to authenticated;

create or replace function public.is_completed(p_participant_id text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select count(distinct stamp_code) = 6
  from public.stamp_claims
  where participant_id = p_participant_id;
$$;

revoke all on function public.is_completed(text) from public;
grant execute on function public.is_completed(text) to anon, authenticated;

create or replace function public.record_scan(
  p_participant_id text,
  p_stamp_code text,
  p_user_agent text default null
)
returns table (claimed boolean, claim_sequence integer, completed boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_claim integer;
begin
  if length(p_participant_id) not between 4 and 64
     or p_stamp_code not in ('river','bridge','fish','island','water','goal') then
    raise exception 'invalid scan';
  end if;

  perform pg_advisory_xact_lock(hashtext(p_participant_id));

  insert into public.scan_events (participant_id, stamp_code, user_agent)
  values (p_participant_id, p_stamp_code, left(p_user_agent, 1000));

  insert into public.stamp_claims (participant_id, stamp_code, sequence)
  select p_participant_id, p_stamp_code, count(*)::integer + 1
  from public.stamp_claims
  where participant_id = p_participant_id
  on conflict (participant_id, stamp_code) do nothing
  returning sequence into inserted_claim;

  return query
  select inserted_claim is not null,
         coalesce(inserted_claim, (
           select sc.sequence from public.stamp_claims sc
           where sc.participant_id = p_participant_id
             and sc.stamp_code = p_stamp_code
         )),
         (select count(distinct sc.stamp_code) = 6
          from public.stamp_claims sc
          where sc.participant_id = p_participant_id);
end;
$$;

revoke all on function public.record_scan(text, text, text) from public;
grant execute on function public.record_scan(text, text, text) to anon, authenticated;

-- アンケート送信。6スポット制覇をサーバー側で確認してから保存する。
-- 戻り値: 'ok' / 'already_submitted' / 'not_completed' / 'invalid_...'
create or replace function public.submit_survey(
  p_participant_id text,
  p_satisfaction integer,
  p_memorable_spot text default null,
  p_comment text default null,
  p_prize_requested boolean default false,
  p_recipient_name text default null,
  p_postal_code text default null,
  p_address text default null,
  p_phone text default null,
  p_consent boolean default false
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_participant text := btrim(coalesce(p_participant_id, ''));
  v_spot text := nullif(btrim(coalesce(p_memorable_spot, '')), '');
  v_comment text := nullif(btrim(coalesce(p_comment, '')), '');
  v_prize boolean := coalesce(p_prize_requested, false);
  v_name text := nullif(btrim(coalesce(p_recipient_name, '')), '');
  v_postal text := nullif(btrim(coalesce(p_postal_code, '')), '');
  v_address text := nullif(btrim(coalesce(p_address, '')), '');
  v_phone text := nullif(btrim(coalesce(p_phone, '')), '');
begin
  if length(v_participant) not between 4 and 64 then
    return 'invalid_participant';
  end if;
  if not public.is_completed(v_participant) then
    return 'not_completed';
  end if;
  if p_satisfaction is null or p_satisfaction not between 1 and 5 then
    return 'invalid_satisfaction';
  end if;
  if v_spot is not null and v_spot not in ('river','bridge','fish','island','water','goal') then
    return 'invalid_spot';
  end if;
  if length(v_comment) > 2000 then
    return 'invalid_comment';
  end if;

  if v_prize then
    if v_name is null or length(v_name) > 100 then return 'invalid_name'; end if;
    if v_postal is null or v_postal !~ '^[0-9]{3}-?[0-9]{4}$' then return 'invalid_postal'; end if;
    if v_address is null or length(v_address) > 300 then return 'invalid_address'; end if;
    if v_phone is null or v_phone !~ '^[0-9]{10,11}$' then return 'invalid_phone'; end if;
    if not coalesce(p_consent, false) then return 'invalid_consent'; end if;
  else
    -- 景品を希望しない回答では個人情報を保存しない
    v_name := null; v_postal := null; v_address := null; v_phone := null;
  end if;

  insert into public.survey_responses (
    completion_participant_id, satisfaction, memorable_spot, comment,
    prize_requested, recipient_name, postal_code, address, phone, consent
  ) values (
    v_participant, p_satisfaction, v_spot, v_comment,
    v_prize, v_name, v_postal, v_address, v_phone, v_prize and coalesce(p_consent, false)
  )
  on conflict (completion_participant_id) do nothing;

  if not found then
    return 'already_submitted';
  end if;
  return 'ok';
end;
$$;

revoke all on function public.submit_survey(text, integer, text, text, boolean, text, text, text, text, boolean) from public;
grant execute on function public.submit_survey(text, integer, text, text, boolean, text, text, text, text, boolean) to anon, authenticated;

commit;

notify pgrst, 'reload schema';

-- ▼ 管理者の登録（Authentication > Users でユーザーを作成した後、メールアドレスを変えて実行）
-- insert into public.admin_users (user_id)
-- select id from auth.users where email = 'admin@example.com'
-- on conflict do nothing;
